import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from "react";
import {ThemeProvider} from "@/theme/ThemeProvider";
import {clsx} from "clsx";
import {Header} from "@/feature/layout/Header";
import {Footer} from "@/feature/layout/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx("bg-background h-full")}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div className="flex flex-col h-full">
          <Header />

          <div className="container">
            {children}
          </div>

          <Footer />
        </div>
      </ThemeProvider>
      </body>
    </html>
  )
}
